# php:
#   preset: laravel
#   disabled:
#     - unused_use
#   finder:
#     not-name:
#       - index.php
#       - server.php
# js:
#   finder:
#     not-name:
#       - webpack.mix.js
# css: true


on: 
  push:
    branches:
    - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: 'ftp.simple2sale.com'
        username: 's2s@simple2sale.com'
        password: 'as[-24##asdfaf'